main.py
from flask import Flask, request, render_template, session, redirect, url_for
import xml.etree.ElementTree as ET
from usuarios_blueprint import usuarios_blueprint
from inicio import cartelera_bp
from pelisenjson import json_bp 
app = Flask(__name__)

# Registrar el blueprint en la aplicación
app.register_blueprint(usuarios_blueprint, url_prefix='/usuarios')
app.register_blueprint(cartelera_bp, url_prefix='/cartelera')
app.register_blueprint(json_bp, url_prefix='/jsonpelis')

class Nodo:
    def __init__(self, dato=None):
        self.dato = dato
        self.siguiente = None


class ListaEnlazada:
    def __init__(self):
        self.cabeza = None

    def esta_vacia(self):
        return self.cabeza is None

    def agregar(self, dato):
        nuevo_nodo = Nodo(dato)
        if self.esta_vacia():
            self.cabeza = nuevo_nodo
        else:
            nodo_actual = self.cabeza
            while nodo_actual.siguiente is not None:
                nodo_actual = nodo_actual.siguiente
            nodo_actual.siguiente = nuevo_nodo

    def remover(self, dato):
        if self.cabeza is None:
            return
        if self.cabeza.dato == dato:
            self.cabeza = self.cabeza.siguiente
            return
        nodo_actual = self.cabeza
        while nodo_actual.siguiente is not None:
            if nodo_actual.siguiente.dato == dato:
                nodo_actual.siguiente = nodo_actual.siguiente.siguiente
                return
            nodo_actual = nodo_actual.siguiente

    def buscar(self, dato):
        nodo_actual = self.cabeza
        while nodo_actual is not None:
            if nodo_actual.dato == dato:
                return True
            nodo_actual = nodo_actual.siguiente
        return False


def cargar_usuarios():
    tree = ET.parse('usuarios.xml')  # Ruta al archivo XML
    root = tree.getroot()
    usuarios = ListaEnlazada()
    for usuario in root.findall('usuario'):
        usuario_info = {}
        for elemento in usuario:
            usuario_info[elemento.tag] = elemento.text
        usuarios.agregar(usuario_info)
    return usuarios



app.secret_key = "tu_clave_secreta" 


@app.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        correo = request.form['correo']
        contrasena = request.form['contrasena']
        usuarios = cargar_usuarios()
        nodo_actual = usuarios.cabeza
        while nodo_actual is not None:
            usuario = nodo_actual.dato
            if usuario['correo'] == correo and usuario['contrasena'] == contrasena:
                session['rol'] = usuario['rol']
                return redirect(url_for('menu'))
            nodo_actual = nodo_actual.siguiente
        error_message = 'Credenciales inválidas'
        return render_template('login.html', error_message=error_message)
    return render_template('login.html')


@app.route('/menu')
def menu():
    if 'rol' in session:
        if session['rol'] == 'administrador':
            return render_template('menu.html')
        elif session['rol'] == 'cliente':
            return render_template('menu.html')
    return redirect(url_for('login'))


@app.route('/logout')
def logout():
    session.pop('rol', None)
    return redirect(url_for('login'))




if __name__ == '__main__':
    app.run(debug=True)

usuarios_blueprint.py
from flask import Flask, render_template, request, Blueprint, redirect, url_for
from xml.etree import ElementTree as etree
from lxml import etree 


app = Flask(__name__)

# Clase para representar un usuario
class Usuario:
    def __init__(self, rol, nombre, apellido, telefono, correo, contrasena):
        self.rol = rol
        self.nombre = nombre
        self.apellido = apellido
        self.telefono = telefono
        self.correo = correo 
        self.contrasena = contrasena

# Clase para representar una lista enlazada de usuarios
class ListaUsuarios:
    def __init__(self):
        self.head = None

    def agregar_usuario(self, usuario):
        if not self.head:
            self.head = usuario
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = usuario

# Crear un objeto Blueprint
usuarios_blueprint = Blueprint('usuarios', __name__)

@usuarios_blueprint.route('/gestionar_usuarios')
def gestionar_usuarios():
    return render_template('gestionar_usarios.html')


@usuarios_blueprint.route('/modificar_usuario')
def modificar_usuario():
    return 'hola' 

@usuarios_blueprint.route('/ver_lista_usuarios')
def ver_lista_usuarios():
    return render_template('ver_lista_usuarios.html')

@usuarios_blueprint.route('/eliminar_usuario')
def eliminar_usuario():
    return render_template('eliminar_usuario.html')

# Ruta para agregar un usuario
@usuarios_blueprint.route('/agregar_usuario', methods=['GET', 'POST'])
def agregar_usuario():
    if request.method == 'POST':
        xml_file = etree.parse('usuarios.xml')
        root = xml_file.getroot()

        # Obtener los datos del formulario
        rol = request.form['rol']
        nombre = request.form['nombre']
        apellido = request.form['apellido']
        telefono = request.form['telefono']
        correo = request.form['correo']
        contrasena = request.form['contrasena']

        # Crear un objeto Usuario con los datos del formulario
        nuevo_usuario = Usuario(rol, nombre, apellido, telefono, correo, contrasena)

        # Agregar el usuario a la lista enlazada
        lista_usuarios.agregar_usuario(nuevo_usuario)

        # Agregar el usuario al archivo XML
        usuario_element = etree.SubElement(root, 'usuario')
        rol_element = etree.SubElement(usuario_element, 'rol')
        rol_element.text = rol
        nombre_element = etree.SubElement(usuario_element, 'nombre')
        nombre_element.text = nombre
        apellido_element = etree.SubElement(usuario_element, 'apellido')
        apellido_element.text = apellido
        telefono_element = etree.SubElement(usuario_element, 'telefono')
        telefono_element.text = telefono
        correo_element = etree.SubElement(usuario_element, 'correo')
        correo_element.text = correo
        contrasena_element = etree.SubElement(usuario_element, 'contrasena')
        contrasena_element.text = contrasena

        # Guardar los cambios en el archivo XML
        xml_file.write('usuarios.xml', encoding='utf-8')

        #return redirect(url_for('usuarios.exito_registro'))

    return render_template('agregar_usuario.html')

def obtener_usuarios():
    tree = etree.parse('usuarios.xml')
    root = tree.getroot()

    usuarios = ListaUsuarios()

    for usuario_element in root.findall('usuario'):
        rol = usuario_element.find('rol').text
        nombre = usuario_element.find('nombre').text
        apellido = usuario_element.find('apellido').text
        telefono = usuario_element.find('telefono').text
        correo = usuario_element.find('correo').text
        contrasena = usuario_element.find('contrasena').text

        usuario = Usuario(rol, nombre, apellido, telefono, correo, contrasena)
        usuarios.append(usuario)

    return usuarios


@usuarios_blueprint.route('/listusers')
def listusers():
    usuarios = obtener_usuarios()
    return render_template('ver_lista_usuarios.html', usuarios=usuarios)
# Registrar el blueprint en la aplicación
app.register_blueprint(usuarios_blueprint)

# Ruta de inicio
@app.route('/')
def index():
    
    return render_template('login.html')

# Crear una instancia de la lista de usuarios
lista_usuarios = ListaUsuarios()

if __name__ == '__main__':
    app.run(debug=True)

templates/admin_menu.html
<!DOCTYPE html>
<html>
<head>
    <title>Menú de administrador</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Menú de administrador</h1>
        <ul class="list-group">
            <li class="list-group-item"><a class="nav-link" href="{{ url_for('gestion_usuarios') }}">Gestión de usuarios</a></li>
            <li class="list-group-item"><a class="nav-link" href="{{ url_for('cartelera./log') }}">Gestión de categorías y películas</a></li>
            <li class="list-group-item"><a class="nav-link" href="#">Gestión de salas</a></li>
            <li class="list-group-item"><a class="nav-link" href="#">Gestión de boletos comprados</a></li>
            <li class="list-group-item"><a class="nav-link" href="/">Salir</a></li>
        </ul>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/agregar_pelicula.html
<!DOCTYPE html>
<html>
<head>
    <title>Agregar Película</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Agregar Película</h1>

        <form action="{{ url_for('cartelera.agregar_pelicula') }}" method="POST">
            <div class="form-group">
                <label for="cate">categoria:</label>
                <input type="text" class="form-control" id="cate" name="cate" required>
            </div>

            <div class="form-group">
                <label for="titulo">Titulo:</label>
                <input type="text" class="form-control" id="titulo" name="titulo" required>
            </div>

            <div class="form-group">
                <label for="director">Director:</label>
                <input type="text" class="form-control" id="director" name="director" required>
            </div>

            <div class="form-group">
                <label for="anio">Año:</label>
                <input type="text" class="form-control" id="anio" name="anio" required>
            </div>

            <div class="form-group">
                <label for="fecha">Fecha:</label>
                <input type="text" class="form-control" id="fecha" name="fecha" required>
            </div>

            <div class="form-group">
                <label for="hora">Hora:</label>
                <input type="text" class="form-control" id="hora" name="hora" required>
            </div>

            <button type="submit" class="btn btn-primary">Agregar</button>
        </form>

        <a href="{{ url_for('cartelera.mostrar_cartelera') }}" class="btn btn-secondary mt-3">Ver Cartelera</a>
    </div>

    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
</body>
</html>

templates/cartelera.html
<!DOCTYPE html>
<html>
<head>
    <title>Cartelera</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Cartelera</h1>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Categoria</th>
                    <th>Titulo</th>
                    <th>Director</th>
                    <th>Año</th>
                    <th>Fecha</th>
                    <th>Hora</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for pelicula in peliculas %}
                <tr>
                    <td>{{ pelicula.cate }}</td>
                    <td>{{ pelicula.titulo }}</td>
                    <td>{{ pelicula.director }}</td>
                    <td>{{ pelicula.anio }}</td>
                    <td>{{ pelicula.fecha }}</td>
                    <td>{{ pelicula.hora }}</td>
                    <td>
                        <a href="{{ url_for('cartelera.editar_pelicula', nombre_pelicula=pelicula.titulo) }}" class="btn btn-primary">Editar</a>
                        <a href="{{ url_for('cartelera.eliminar_pelicula', nombre_pelicula=pelicula.titulo) }}" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="d-flex justify-content-between">
            <a href="{{ url_for('cartelera.agregar_pelicula') }}" class="btn btn-success btn-block text-center">Agregar Pelicula</a>
            <form action="{{ url_for('cartelera.agregar_pelicula') }}" method="post" enctype="multipart/form-data">
                
            </form>
        </div>
    </div>

    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
</body>
</html>

templates/carteleraCliente.html
<!DOCTYPE html>
<html>
<head>
    <title>Cartelera</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Cartelera</h1>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Categoria</th>
                    <th>Titulo</th>
                    <th>Director</th>
                    <th>Año</th>
                    <th>Fecha</th>
                    <th>Hora</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for pelicula in peliculas %}
                <tr>
                    <td>{{ pelicula.cate }}</td>
                    <td>{{ pelicula.titulo }}</td>
                    <td>{{ pelicula.director }}</td>
                    <td>{{ pelicula.anio }}</td>
                    <td>{{ pelicula.fecha }}</td>
                    <td>{{ pelicula.hora }}</td>
                    <td>
                        <button onclick="comprarBoleto('{{ pelicula.cate }}', '{{ pelicula.titulo }}')">Comprar</button>
                        <button onclick="AgregarFavoritos('{{ pelicula.cate }}', '{{ pelicula.titulo }}')">Favoritos</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <button onclick="verCompras()">Ver Compras</button>
        <button onclick="verFavoritos()">Ver Favoritos</button>
    </div>

    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.all.min.js"></script>
    <script>
        function comprarBoleto(categoria, titulo) {
            Swal.fire({
                title: 'Comprar boleto',
                text: '¿Deseas comprar el boleto para la película ' + titulo + '?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: 'Sí, comprar',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    var url = "{{ url_for('cartelera.comprar_boleto') }}"; // Ajusta la URL para realizar la compra en tu backend
                    var formData = new FormData();
                    formData.append('categoria', categoria);
                    formData.append('titulo', titulo);

                    fetch(url, {
                        method: 'POST',
                        body: formData
                    })
                    .then(response => {
                        if (!response.ok) {
                            throw new Error('Error al realizar la compra');
                        }
                        return response.json();
                    })
                    .then(data => {
                        Swal.fire({
                            title: '¡Compra exitosa!',
                            text: 'Se ha realizado la compra del boleto para la película ' + titulo,
                            icon: 'success'
                        });
                    })
                    .catch(error => {
                        console.error(error);
                        Swal.fire({
                            title: 'Error',
                            text: 'Ocurrió un error al realizar la compra',
                            icon: 'error'
                        });
                    });
                }
            });
        }

        function verCompras() {
            // Realizar petición AJAX para obtener las compras realizadas
            fetch("{{ url_for('cartelera.obtener_compras') }}")
                .then(response => response.json())
                .then(data => {
                    // Construir el contenido de la ventana emergente con las compras
                    let contenido = '<h2>Compras realizadas</h2>';
                    if (data.length > 0) {
                        contenido += '<ul>';
                        data.forEach(compra => {
                            contenido += '<li>Número de boleto: ' + compra.numero_boleto + '</li>';
                            contenido += '<li>Categoría: ' + compra.categoria + '</li>';
                            contenido += '<li>Título: ' + compra.titulo + '</li>';
                            contenido += '<br>';
                        });
                        contenido += '</ul>';
                    } else {
                        contenido += '<p>No se han realizado compras</p>';
                    }

                    // Mostrar la ventana emergente con el contenido generado
                    Swal.fire({
                        title: 'Compras realizadas',
                        html: contenido,
                        icon: 'info'
                    });
                })
                .catch(error => console.error(error));
        }
    </script>
    <script>
        function AgregarFavoritos(categoria, titulo) {
            Swal.fire({
                title: 'Agregar Favorito',
                text: '¿Deseas agergar a favoritos la película ' + titulo + '?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: 'Sí, agregar',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    var url = "{{ url_for('cartelera.lista_favorito') }}"; 
                    var formData = new FormData();
                    formData.append('categoria', categoria);
                    formData.append('titulo', titulo);

                    fetch(url, {
                        method: 'POST',
                        body: formData
                    })
                    .then(response => {
                        if (!response.ok) {
                            throw new Error('Error al realizar la solicitud');
                        }
                        return response.json();
                    })
                    .then(data => {
                        Swal.fire({
                            title: '¡Solicitud exitosa!',
                            text: 'Se a agregado a tu lista de favoritos ' + titulo,
                            icon: 'success'
                        });
                    })
                    .catch(error => {
                        console.error(error);
                        Swal.fire({
                            title: 'Error',
                            text: 'Ocurrió un error al realizar la solicitud',
                            icon: 'error'
                        });
                    });
                }
            });
        }

        function verFavoritos() {
            
            fetch("{{ url_for('cartelera.obtener_favorito') }}")
                .then(response => response.json())
                .then(data => {
                    // Construir el contenido de la ventana emergente con las favoritos
                    let contenido = '<h2>Lista Favoritos</h2>';
                    if (data.length > 0) {
                        contenido += '<ul>';
                        data.forEach(compra => {
                            contenido += '<li>Número de boleto: ' + compra.numero_boleto + '</li>';
                            contenido += '<li>Categoría: ' + compra.categoria + '</li>';
                            contenido += '<li>Título: ' + compra.titulo + '</li>';
                            contenido += '<br>';
                        });
                        contenido += '</ul>';
                    } else {
                        contenido += '<p>No se han realizado solicitud</p>';
                    }

                    // Mostrar la ventana emergente con el contenido generado
                    Swal.fire({
                        title: 'Lista Favoritos',
                        html: contenido,
                        icon: 'info'
                    });
                })
                .catch(error => console.error(error));
        }
    </script>


</body>
</html>

templates/cliente_menu.html
<!DOCTYPE html>
<html>
<head>
    <title>Menú de cliente</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Menú de cliente</h1>
        <ul class="list-group">
            <li class="list-group-item"><a href="{{ url_for('cartelera.agregar_pelicula') }}">Ver listado de películas</a></li>
            <li class="list-group-item"><a href="#">Marcar película como favorita</a></li>
            <li class="list-group-item"><a href="#">Comprar boletos</a></li>
            <li class="list-group-item"><a href="#">Mostrar historial de compras</a></li>
            <li class="list-group-item"><a href="#">Salir</a></li>
        </ul>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/editar_pelicula.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar Película</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Editar Película</h1>

        <form method="POST" action="{{ url_for('cartelera.editar_pelicula', nombre_pelicula=pelicula.titulo) }}">

            <div class="form-group">
                <label for="titulo">Titulo:</label>
                <input type="text" class="form-control" id="titulo" name="titulo" value="{{ pelicula.nombre }}" required>
            </div>

            <div class="form-group">
                <label for="cate">Género:</label>
                <input type="text" class="form-control" id="cate" name="cate" value="{{ pelicula.cate }}" required>
            </div>

            <div class="form-group">
                <label for="director">Director:</label>
                <input type="text" class="form-control" id="director" name="director" value="{{ pelicula.director }}" required>
            </div>

            <div class="form-group">
                <label for="anio">Año:</label>
                <input type="text" class="form-control" id="anio" name="anio" value="{{ pelicula.duracion }}" required>
            </div>

            <div class="form-group">
                <label for="fecha">Fecha:</label>
                <input type="text" class="form-control" id="fecha" name="fecha" value="{{ pelicula.horario }}" required>
            </div>

            <div class="form-group">
                <label for="hora">Hora:</label>
                <input type="text" class="form-control" id="hora" name="hora" value="{{ pelicula.horario }}" required>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>

        <a href="{{ url_for('cartelera.mostrar_cartelera') }}" class="btn btn-secondary">Cancelar</a>
    </div>

    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
</body>
</html>

templates/favoritas.html
<!DOCTYPE html>
<html>
<head>
    <title>Películas Favoritas</title>
</head>
<body>
    <h1>Películas Favoritas</h1>
    <ul>
        {% for pelicula in peliculas %}
            <li>{{ pelicula.titulo }} - {{ pelicula.fecha }} - {{ pelicula.hora }}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/formulario_agregar_usuario.html
<!DOCTYPE html>
<html>
<head>
    <title>Agregar usuario</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Agregar usuario</h1>
        <form method="POST" action="/agregar_usuario">
            <div class="form-group">
                <label for="rol">Rol:</label>
                <input type="text" id="rol" name="rol" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="nombre">Nombre:</label>
                <input type="text" id="nombre" name="nombre" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="apellido">Apellido:</label>
                <input type="text" id="apellido" name="apellido" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="telefono">Teléfono:</label>
                <input type="text" id="telefono" name="telefono" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="correo">Correo:</label>
                <input type="email" id="correo" name="correo" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="contrasena">Contraseña:</label>
                <input type="password" id="contrasena" name="contrasena" class="form-control" required>
            </div>

            <button type="submit" class="btn btn-primary">Agregar</button>
        </form>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/historial_compras.html
<!DOCTYPE html>
<html>
<head>
    <title>Historial de Compras</title>
</head>
<body>
    <h1>Historial de Compras</h1>
    <table>
        <tr>
            <th>Película</th>
            <th>Cantidad</th>
            <th>Fecha</th>
        </tr>
        {% for compra in peliculas %}
        <tr>
            <td>{{ compra.pelicula.titulo }}</td>
            <td>{{ compra.cantidad }}</td>
            <td>{{ compra.fecha }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Inicio</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Bienvenido a la cartelera de películas</h1>
        <a class="btn btn-primary mt-3" href="{{ url_for('cartelera.mostrar_cartelera') }}">Ver Cartelera</a>
        <a class="btn btn-success mt-3" href="{{ url_for('cartelera.agregar_pelicula') }}">Agregar Película</a>
    </div>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Iniciar sesión</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Iniciar sesión</h1>
        
        {% if error_message %}
            <div class="alert alert-danger mt-4" role="alert">
                {{ error_message }}
            </div>
        {% endif %}
        
        <form method="POST" action="/">
            <div class="form-group">
                <label for="correo">Correo electrónico</label>
                <input type="text" name="correo" id="correo" class="form-control" placeholder="Correo electrónico">
            </div>
            <div class="form-group">
                <label for="contrasena">Contraseña</label>
                <input type="password" name="contrasena" id="contrasena" class="form-control" placeholder="Contraseña">
            </div>
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </form>
        
        {% if redirect %}
            <script>
                alert("Credenciales inválidas");
                window.location.href = "/login";
            </script>
        {% endif %}
    </div>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/menu.html
<!DOCTYPE html>
<html>
<head>
    <title>Menú</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        {% if session['rol'] == 'administrador' %}
            <h1 class="mt-4">Menú del administrador</h1>
            <ul class="list-group">
                <a href="{{ url_for('usuarios.gestionar_usuarios') }}" class="list-group-item">Gestionar usuarios</a>
                <a href="{{ url_for('cartelera.index') }}" class="list-group-item">Gestionar películas</a>
                <a href="/gestionar_salas" class="list-group-item">Gestionar salas</a>
                <a href="{{ url_for('jsonpelis.peliculas') }}" class="list-group-item">Peliculas 2.0</a>
                <a href="/gestionar_boletos" class="list-group-item">Gestionar boletos</a>
                <a href="/logout" class="list-group-item">Salir</a>
            </ul>
        {% elif session['rol'] == 'cliente' %}
            <h1 class="mt-4">Menú del cliente</h1>
            <ul class="list-group">
                <a href="{{ url_for('cartelera.mostrar_carteleracl') }}" class="list-group-item">Películas</a>
                <a href="/salas" class="list-group-item">Gestionar salas</a>
                <a href="{{ url_for('jsonpelis.peliculas') }}" class="list-group-item">Peliculas 2.0</a>
                <a href="/gestionar_boletos" class="list-group-item">Gestionar boletos</a>
                <a href="/logout" class="list-group-item">Salir</a>
            </ul>
        {% else %}
            <h1 class="mt-4">Sesión inválida</h1>
        {% endif %}
    </div>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/ver_lista_usuarios.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Usuarios</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Lista de Usuarios</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Rol</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Teléfono</th>
                    <th>Correo Electrónico</th>
                    <th>Contraseña</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                <tr>
                    <td>{{ usuario.rol }}</td>
                    <td>{{ usuario.nombre }}</td>
                    <td>{{ usuario.apellido }}</td>
                    <td>{{ usuario.telefono }}</td>
                    <td>{{ usuario.correo }}</td>
                    <td>{{ usuario.contrasena }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>